services:
  - type: web
    name: rag-toy-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn server.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENSEARCH_HOST
        sync: false
      - key: OPENSEARCH_USER
        sync: false
      - key: OPENSEARCH_PASSWD
        sync: false
      - key: OPENSEARCH_PORT
        sync: false
      - key: OPENSEARCH_INDEX
        sync: false
      - key: CLOVA_API_TOKEN
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
